site_name: Build an AI Agent
site_url: https://rob212.github.io/rob-agent/
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Basic concepts: basic-concepts.md
  - Building your first agent: building-your-first-agent.md
  - Tools:
      - Tool definitions: tool-definitions.md
      - Web Search tool: implementing-a-web-search-tool.md
      - MCP: mcp.md
  - Loop:
      - ReAct: react.md
      - ExecutionContext: execution-context.md
      - Tool Abstraction: tool-abstraction.md
      - LLM Communication Layer: llm-communication-layer.md
  - Building your second agent: building-your-second-agent.md
  - AWS Strands: aws-strands.md
